-- AlterTable
ALTER TABLE "List" ALTER COLUMN "created_at" SET DATA TYPE BIGINT,
ALTER COLUMN "updated_at" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "created_at" SET DATA TYPE BIGINT,
ALTER COLUMN "updated_at" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "created_at" SET DATA TYPE BIGINT,
ALTER COLUMN "updated_at" SET DATA TYPE BIGINT;
